#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Soft.Crap.Android.Resource", IsApplication=true)]

namespace Soft.Crap.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040017
			public const int Black = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int Blue = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int Gray = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int Navy = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int Orange = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int Soft_Crap_BarBackground = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int Soft_Crap_BarForeground = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int Soft_Crap_ImageBackground = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int Soft_Crap_InnerFrame = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int Soft_Crap_OuterFrame = 2130968610;
			
			// aapt resource value: 0x7f04001c
			public const int Transparent = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int White = 2130968605;
			
			// aapt resource value: 0x7f04000e
			public const int common_action_bar_splitter = 2130968590;
			
			// aapt resource value: 0x7f040023
			public const int common_google_signin_btn_text_dark = 2130968611;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_signin_btn_text_dark_default = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int common_google_signin_btn_text_dark_disabled = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int common_google_signin_btn_text_dark_focused = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int common_google_signin_btn_text_dark_pressed = 2130968592;
			
			// aapt resource value: 0x7f040024
			public const int common_google_signin_btn_text_light = 2130968612;
			
			// aapt resource value: 0x7f040013
			public const int common_google_signin_btn_text_light_default = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int common_google_signin_btn_text_light_disabled = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int common_google_signin_btn_text_light_focused = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int common_google_signin_btn_text_light_pressed = 2130968596;
			
			// aapt resource value: 0x7f040025
			public const int common_plus_signin_btn_text_dark = 2130968613;
			
			// aapt resource value: 0x7f040006
			public const int common_plus_signin_btn_text_dark_default = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int common_plus_signin_btn_text_dark_disabled = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_plus_signin_btn_text_dark_focused = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_plus_signin_btn_text_dark_pressed = 2130968583;
			
			// aapt resource value: 0x7f040026
			public const int common_plus_signin_btn_text_light = 2130968614;
			
			// aapt resource value: 0x7f04000a
			public const int common_plus_signin_btn_text_light_default = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int common_plus_signin_btn_text_light_disabled = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_plus_signin_btn_text_light_focused = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int common_plus_signin_btn_text_light_pressed = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int place_autocomplete_prediction_primary_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int place_autocomplete_prediction_primary_text_highlight = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int place_autocomplete_prediction_secondary_text = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int place_autocomplete_search_hint = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int place_autocomplete_search_text = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int place_autocomplete_separator = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int place_autocomplete_button_padding = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int place_autocomplete_powered_by_google_height = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int place_autocomplete_powered_by_google_start = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int place_autocomplete_prediction_height = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int place_autocomplete_prediction_horizontal_margin = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int place_autocomplete_prediction_primary_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int place_autocomplete_prediction_secondary_text = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int place_autocomplete_progress_horizontal_margin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int place_autocomplete_progress_size = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int place_autocomplete_separator_start = 2131034119;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AttributesButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_circle_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_circle_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_circle_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_crop_image_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_crop_image_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_fit_image_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_fit_image_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_grid_view_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_grid_view_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_list_view_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_list_view_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CaptureButton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_full_open_on_phone = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_dark_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_dark_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_dark_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_icon_dark_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_icon_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_icon_light_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_icon_light_focused = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_icon_light_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_icon_light_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_dark_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_dark_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_text_dark_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_dark_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_text_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_google_signin_btn_text_light_disabled = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_google_signin_btn_text_light_focused = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_google_signin_btn_text_light_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_google_signin_btn_text_light_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_ic_googleplayservices = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_icon_dark_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_icon_dark_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_icon_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_icon_light_disabled = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_icon_light_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_icon_light_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_icon_light_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_text_dark_disabled = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_plus_signin_btn_text_dark_focused = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_text_dark_normal = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_text_dark_pressed = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int common_plus_signin_btn_text_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int common_plus_signin_btn_text_light_disabled = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int common_plus_signin_btn_text_light_focused = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int common_plus_signin_btn_text_light_normal = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int common_plus_signin_btn_text_light_pressed = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int CorruptObject = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int CrapAppIcon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int CrapAppSplash = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int CropImageButton = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int FitImageButton = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int GridViewButton = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_menu_camera = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_menu_delete = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_menu_find_holo_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_menu_moreoverflow_normal_holo_dark = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_menu_rotate = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_menu_search = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_perm_group_user_dictionary = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ListViewButton = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int perm_group_display = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int perm_group_user_dictionary = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int places_ic_clear = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int places_ic_search = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int powered_by_google_dark = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int powered_by_google_light = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int progress_circle_1 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int progress_circle_2 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int progress_circle_3 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int progress_circle_4 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int progress_circle_5 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int progress_circle_6 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int progress_circle_7 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int progress_circle_8 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int progress_sphere_1 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int progress_sphere_2 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int progress_sphere_3 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int progress_sphere_4 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ProgressCircle = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ProgressSphere = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int RotateButton = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int SplashLayers = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int type_audio = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int type_image = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int type_video = 2130837597;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0038
			public const int AddObjectItem = 2131361848;
			
			// aapt resource value: 0x7f0a0015
			public const int AttributesButton = 2131361813;
			
			// aapt resource value: 0x7f0a0024
			public const int BackgroundFrame = 2131361828;
			
			// aapt resource value: 0x7f0a0019
			public const int BrowseFooterFragment = 2131361817;
			
			// aapt resource value: 0x7f0a000e
			public const int CaptureButton = 2131361806;
			
			// aapt resource value: 0x7f0a003b
			public const int CropImageItem = 2131361851;
			
			// aapt resource value: 0x7f0a0011
			public const int CropThumbnailButton = 2131361809;
			
			// aapt resource value: 0x7f0a0017
			public const int EditImageFragment = 2131361815;
			
			// aapt resource value: 0x7f0a003d
			public const int EditSourceItem = 2131361853;
			
			// aapt resource value: 0x7f0a0014
			public const int EditedImage = 2131361812;
			
			// aapt resource value: 0x7f0a003c
			public const int FitImageItem = 2131361852;
			
			// aapt resource value: 0x7f0a0012
			public const int FitThumbnailButton = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int FooterScrollText = 2131361811;
			
			// aapt resource value: 0x7f0a000f
			public const int GridViewButton = 2131361807;
			
			// aapt resource value: 0x7f0a003e
			public const int GridViewItem = 2131361854;
			
			// aapt resource value: 0x7f0a0023
			public const int InnerFrame = 2131361827;
			
			// aapt resource value: 0x7f0a0010
			public const int ListViewButton = 2131361808;
			
			// aapt resource value: 0x7f0a003f
			public const int ListViewItem = 2131361855;
			
			// aapt resource value: 0x7f0a003a
			public const int MoreOptionsItem = 2131361850;
			
			// aapt resource value: 0x7f0a0022
			public const int ObjectDescription = 2131361826;
			
			// aapt resource value: 0x7f0a0021
			public const int ObjectDetails = 2131361825;
			
			// aapt resource value: 0x7f0a001a
			public const int ObjectGridView = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int ObjectListView = 2131361819;
			
			// aapt resource value: 0x7f0a001e
			public const int ObjectLocation = 2131361822;
			
			// aapt resource value: 0x7f0a0025
			public const int ObjectThumbnail = 2131361829;
			
			// aapt resource value: 0x7f0a001d
			public const int ObjectTime = 2131361821;
			
			// aapt resource value: 0x7f0a0018
			public const int OuterFrame = 2131361816;
			
			// aapt resource value: 0x7f0a002e
			public const int PlayedVideo = 2131361838;
			
			// aapt resource value: 0x7f0a0035
			public const int ProgressCount = 2131361845;
			
			// aapt resource value: 0x7f0a0016
			public const int RotateButton = 2131361814;
			
			// aapt resource value: 0x7f0a0037
			public const int ScaleTypeItem = 2131361847;
			
			// aapt resource value: 0x7f0a0039
			public const int SearchObjectsItem = 2131361849;
			
			// aapt resource value: 0x7f0a0020
			public const int SourceDescription = 2131361824;
			
			// aapt resource value: 0x7f0a0033
			public const int SourceDetails = 2131361843;
			
			// aapt resource value: 0x7f0a0032
			public const int SourceEnabled = 2131361842;
			
			// aapt resource value: 0x7f0a002f
			public const int SourceGridView = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int SourceListView = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int SourceThumbnail = 2131361841;
			
			// aapt resource value: 0x7f0a0034
			public const int SplashProgress = 2131361844;
			
			// aapt resource value: 0x7f0a000d
			public const int TextureView = 2131361805;
			
			// aapt resource value: 0x7f0a001c
			public const int TypeDescription = 2131361820;
			
			// aapt resource value: 0x7f0a001f
			public const int TypeThumbnail = 2131361823;
			
			// aapt resource value: 0x7f0a0036
			public const int ViewTypeItem = 2131361846;
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a000a
			public const int auto = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int dark = 2131361803;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int icon_only = 2131361799;
			
			// aapt resource value: 0x7f0a000c
			public const int light = 2131361804;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a0028
			public const int place_autocomplete_clear_button = 2131361832;
			
			// aapt resource value: 0x7f0a002a
			public const int place_autocomplete_powered_by_google = 2131361834;
			
			// aapt resource value: 0x7f0a002c
			public const int place_autocomplete_prediction_primary_text = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int place_autocomplete_prediction_secondary_text = 2131361837;
			
			// aapt resource value: 0x7f0a002b
			public const int place_autocomplete_progress = 2131361835;
			
			// aapt resource value: 0x7f0a0026
			public const int place_autocomplete_search_button = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int place_autocomplete_search_input = 2131361831;
			
			// aapt resource value: 0x7f0a0029
			public const int place_autocomplete_separator = 2131361833;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a0008
			public const int standard = 2131361800;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0009
			public const int wide = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddImageLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BrowseFooterFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditImageFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditImageLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ObjectCellLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ObjectGridLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ObjectListLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ObjectRowLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ObjectThumbnailInclude = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int place_autocomplete_fragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int place_autocomplete_item_powered_by_google = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int place_autocomplete_item_prediction = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int place_autocomplete_progress = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PlayVideoLayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SourceGridLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SourceListLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SourceRowLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SplashScreenLayout = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int BrowseViewPopupMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int ObjectViewOptionsMenu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int ScaleTypeCheckableMenu = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int SourceViewOptionsMenu = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int ViewTypeCheckableMenu = 2131296260;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060021
			public const int AddObjectItem = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int AlertCancelButton = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int AlertCloseButton = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int AlertDeleteButton = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int AlertRecaptureButton = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int ApplicationName = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int AudioObjectType = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int CorruptObjectFormat = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int CropImageItem = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int DeleteObjectItem = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int DeleteReceiptQuestion = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int DeleteReceiptTitle = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int EditSourceItem = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int FitImageItem = 2131099694;
			
			// aapt resource value: 0x7f060030
			public const int GridViewItem = 2131099696;
			
			// aapt resource value: 0x7f06002f
			public const int ImageObjectType = 2131099695;
			
			// aapt resource value: 0x7f060032
			public const int ListViewItem = 2131099698;
			
			// aapt resource value: 0x7f060034
			public const int MoreOptionsItem = 2131099700;
			
			// aapt resource value: 0x7f060033
			public const int NoCameraApplicationInfo = 2131099699;
			
			// aapt resource value: 0x7f060031
			public const int ScaleTypeItem = 2131099697;
			
			// aapt resource value: 0x7f060035
			public const int ScrollTextFormat = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int SearchObjectsItem = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int SplashTextFormat = 2131099703;
			
			// aapt resource value: 0x7f060039
			public const int VideoErrorFormat = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int VideoObjectType = 2131099704;
			
			// aapt resource value: 0x7f06003a
			public const int ViewTypeItem = 2131099706;
			
			// aapt resource value: 0x7f060003
			public const int auth_google_play_services_client_facebook_display_name = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int auth_google_play_services_client_google_display_name = 2131099650;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_play_services_api_unavailable_text = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_enable_button = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_enable_text = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_enable_title = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_install_button = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_install_text_phone = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_install_text_tablet = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_title = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_invalid_account_text = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int common_google_play_services_invalid_account_title = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_network_error_text = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_network_error_title = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_notification_ticker = 2131099653;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_restricted_profile_text = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int common_google_play_services_restricted_profile_title = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int common_google_play_services_sign_in_failed_text = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_play_services_sign_in_failed_title = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_unknown_issue = 2131099652;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_unsupported_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_unsupported_title = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_update_button = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_update_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_update_title = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_updating_text = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_updating_title = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_wear_update_text = 2131099663;
			
			// aapt resource value: 0x7f060019
			public const int common_open_on_phone = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int common_signin_button_text = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int common_signin_button_text_long = 2131099680;
			
			// aapt resource value: 0x7f060001
			public const int place_autocomplete_clear_button = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int place_autocomplete_search_hint = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int Soft_Crap = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int Soft_Crap_Camera = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Soft_Crap_Splash = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int Soft_Crap_TextAppearance_Holo_WindowTitle = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int Soft_Crap_TextAppearance_StatusBar_Title = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int Soft_Crap_Widget_ActionBar = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int WindowTitle = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
