#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Soft.Crap.Android.Resource", IsApplication=true)]

namespace Soft.Crap.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int Black = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Gray = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Navy = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Orange = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int Soft_Crap_BarBackground = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Soft_Crap_BarForeground = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Soft_Crap_ImageBackground = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Soft_Crap_InnerFrame = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Soft_Crap_OuterFrame = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int Transparent = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int White = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AttributesButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_circle_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_circle_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_circle_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_crop_image_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_crop_image_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_fit_image_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_fit_image_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_grid_view_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_grid_view_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_list_view_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_list_view_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CaptureButton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int CorruptObject = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int CrapAppIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int CrapAppSplash = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int CropImageButton = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int FitImageButton = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int GridViewButton = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_menu_camera = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_menu_delete = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_menu_find_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_menu_moreoverflow_normal_holo_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_menu_rotate = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_menu_search = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_perm_group_user_dictionary = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ListViewButton = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int perm_group_display = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int perm_group_user_dictionary = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int progress_circle_1 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int progress_circle_2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int progress_circle_3 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int progress_circle_4 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int progress_circle_5 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int progress_circle_6 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int progress_circle_7 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int progress_circle_8 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int progress_sphere_1 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int progress_sphere_2 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int progress_sphere_3 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int progress_sphere_4 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ProgressCircle = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ProgressSphere = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int RotateButton = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int SplashLayers = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int type_audio = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int type_image = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int type_video = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080023
			public const int AddObjectItem = 2131230755;
			
			// aapt resource value: 0x7f080008
			public const int AttributesButton = 2131230728;
			
			// aapt resource value: 0x7f080017
			public const int BackgroundFrame = 2131230743;
			
			// aapt resource value: 0x7f08000c
			public const int BrowseFooterFragment = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int CaptureButton = 2131230721;
			
			// aapt resource value: 0x7f080026
			public const int CropImageItem = 2131230758;
			
			// aapt resource value: 0x7f080004
			public const int CropThumbnailButton = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int EditImageFragment = 2131230730;
			
			// aapt resource value: 0x7f080028
			public const int EditSourceItem = 2131230760;
			
			// aapt resource value: 0x7f080007
			public const int EditedImage = 2131230727;
			
			// aapt resource value: 0x7f080027
			public const int FitImageItem = 2131230759;
			
			// aapt resource value: 0x7f080005
			public const int FitThumbnailButton = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int FooterScrollText = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int GridViewButton = 2131230722;
			
			// aapt resource value: 0x7f080029
			public const int GridViewItem = 2131230761;
			
			// aapt resource value: 0x7f080016
			public const int InnerFrame = 2131230742;
			
			// aapt resource value: 0x7f080003
			public const int ListViewButton = 2131230723;
			
			// aapt resource value: 0x7f08002a
			public const int ListViewItem = 2131230762;
			
			// aapt resource value: 0x7f080025
			public const int MoreOptionsItem = 2131230757;
			
			// aapt resource value: 0x7f080020
			public const int ObjectCount = 2131230752;
			
			// aapt resource value: 0x7f080015
			public const int ObjectDescription = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int ObjectDetails = 2131230740;
			
			// aapt resource value: 0x7f08000d
			public const int ObjectGridView = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int ObjectListView = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int ObjectLocation = 2131230737;
			
			// aapt resource value: 0x7f080018
			public const int ObjectThumbnail = 2131230744;
			
			// aapt resource value: 0x7f080010
			public const int ObjectTime = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int OuterFrame = 2131230731;
			
			// aapt resource value: 0x7f080019
			public const int PlayedVideo = 2131230745;
			
			// aapt resource value: 0x7f080009
			public const int RotateButton = 2131230729;
			
			// aapt resource value: 0x7f080022
			public const int ScaleTypeItem = 2131230754;
			
			// aapt resource value: 0x7f080024
			public const int SearchObjectsItem = 2131230756;
			
			// aapt resource value: 0x7f080013
			public const int SourceDescription = 2131230739;
			
			// aapt resource value: 0x7f08001e
			public const int SourceDetails = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int SourceEnabled = 2131230749;
			
			// aapt resource value: 0x7f08001a
			public const int SourceGridView = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int SourceListView = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int SourceThumbnail = 2131230748;
			
			// aapt resource value: 0x7f08001f
			public const int SplashProgress = 2131230751;
			
			// aapt resource value: 0x7f080000
			public const int TextureView = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int TypeDescription = 2131230735;
			
			// aapt resource value: 0x7f080012
			public const int TypeThumbnail = 2131230738;
			
			// aapt resource value: 0x7f080021
			public const int ViewTypeItem = 2131230753;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddImageLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BrowseFooterFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditImageFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditImageLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ObjectCellLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ObjectGridLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ObjectListLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ObjectRowLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ObjectThumbnailInclude = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PlayVideoLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SourceGridLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SourceListLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SourceRowLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SplashScreenLayout = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int BrowseViewPopupMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ObjectViewOptionsMenu = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ScaleTypeCheckableMenu = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int SourceViewOptionsMenu = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int ViewTypeCheckableMenu = 2131165188;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int AddObjectItem = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AlertCancelButton = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int AlertCloseButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int AlertDeleteButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int AlertRecaptureButton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ApplicationName = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int AudioObjectType = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int CorruptObjectFormat = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int CropImageItem = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int DeleteObjectItem = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int DeleteReceiptQuestion = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int DeleteReceiptTitle = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int EditSourceItem = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int FitImageItem = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int GridViewItem = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int ImageObjectType = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int ListViewItem = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int MoreOptionsItem = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int NoCameraApplicationInfo = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int ScaleTypeItem = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int ScrollTextFormat = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int SearchObjectsItem = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int SplashTextFormat = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int VideoErrorFormat = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int VideoObjectType = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int ViewTypeItem = 2131034137;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int Soft_Crap = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Soft_Crap_Camera = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Soft_Crap_Splash = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int Soft_Crap_TextAppearance_Holo_WindowTitle = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int Soft_Crap_TextAppearance_StatusBar_Title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int Soft_Crap_Widget_ActionBar = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int WindowTitle = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
